name: pyemu
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.8
  - numpy>=1.15.0
  - pandas
  # optional
  - matplotlib>=1.4.0
  - pyshp
  - jinja2
  # tests
  - coveralls
  - nose-timer
  - pytest-xdist
  - nbmake
  - shapely
