name: pyemu
channels:
  - defaults
dependencies:  
  - numpy 
  - pandas 
  - pyshp
  - nose-timer
  - nbsphinx
  - matplotlib
  - coverage
  - scipy
  - shapely>=1.8
  - tomli
  - pillow=9.3
  - pip
